# Generated by Django 5.0.3 on 2024-06-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
