# Generated by Django 5.0.3 on 2024-06-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasal', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='searched',
            field=models.CharField(default='', max_length=60),
        ),
    ]
