# Generated by Django 5.0.3 on 2024-06-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasal', '0004_profile_searched'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommended_products',
            field=models.TextField(default='[]'),
        ),
    ]
