# Generated by Django 5.0.3 on 2024-06-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasal', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
